# Generated by Django 4.2.7 on 2024-05-03 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('suppliers', '0001_initial'),
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор поставщика'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='product',
            field=models.ManyToManyField(to='products.product', verbose_name='Продукт'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='suppliers.supplier', verbose_name='Поставщик'),
        ),
    ]
